// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package stat

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/stat/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/stat/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/stat/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitStatModule(db *gorm.DB) *Module {
	statDao := dao.NewStatDao(db)
	statRepository := repo.NewStatRepository(statDao)
	statService := service.NewStatService(statRepository)
	module := &Module{
		Svc: statService,
	}
	return module
}

// wire.go:

var StatProviders = wire.NewSet(service.NewStatService, repo.NewStatRepository, dao.NewStatDao, wire.Bind(new(service.IStatService), new(*service.StatService)), wire.Bind(new(repo.IStatRepository), new(*repo.StatRepository)), wire.Bind(new(dao.IStatDao), new(*dao.StatDao)))
