// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/attachments"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/categories"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/comments"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/oss"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/post_category"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/posts"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/tags"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/users"
	"github.com/dzsdbsdxq/dz-gin-blog/app/initialize"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initializeApp() (*gin.Engine, error) {
	db := initialize.NewMysql()
	module := posts.InitPostModule(db)
	postHandler := module.Hdl
	usersModule := users.InitUsersModule(db)
	userHandler := usersModule.Hdl
	ossModule := oss.InitOssModule()
	attachmentsModule := attachments.InitAttachmentsModule(db, ossModule)
	attachmentsHandler := attachmentsModule.Hdl
	post_categoryModule := post_category.InitPostCategoriesModule(db)
	categoriesModule := categories.InitCategoriesModule(db, post_categoryModule)
	categoryHandler := categoriesModule.Hdl
	tagsModule := tags.InitTagsModule(db)
	tagsHandler := tagsModule.Hdl
	commentsModule := comments.InitCommentsModule(db, module)
	commentsHandler := commentsModule.Hdl
	engine, err := initialize.NewGinEngine(postHandler, userHandler, attachmentsHandler, categoryHandler, tagsHandler, commentsHandler)
	if err != nil {
		return nil, err
	}
	return engine, nil
}
