// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package install

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/install/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitInstallModule(db *gorm.DB) *Module {
	installService := service.NewInstallService(db)
	module := &Module{
		Svc:  installService,
		ISvc: installService,
	}
	return module
}

// wire.go:

var InstallProviders = wire.NewSet(service.NewInstallService, wire.Bind(new(service.IInstallService), new(*service.InstallService)))
