// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package themes

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/setting"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/themes/controller"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/themes/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/themes/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/themes/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitThemesModule(db *gorm.DB, settingModule *setting.Module) *Module {
	themesDao := dao.NewThemesDao(db)
	themesRepository := repo.NewThemesRepository(themesDao)
	themesService := service.NewThemesService(themesRepository)
	iSettingService := settingModule.Svc
	themesHandler := controller.NewThemesHandler(themesService, iSettingService)
	module := &Module{
		Svc: themesService,
		Hdl: themesHandler,
	}
	return module
}

// wire.go:

var ThemeProviders = wire.NewSet(controller.NewThemesHandler, service.NewThemesService, repo.NewThemesRepository, dao.NewThemesDao, wire.Bind(new(service.IThemesService), new(*service.ThemesService)), wire.Bind(new(repo.IThemesRepository), new(*repo.ThemesRepository)), wire.Bind(new(dao.IThemesDao), new(*dao.ThemesDao)))
