// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logs

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/logs/controller"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/logs/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/logs/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/logs/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitLogsModule(db *gorm.DB) *Module {
	logsDao := dao.NewLogsDao(db)
	logsRepository := repo.NewLogsRepository(logsDao)
	logService := service.NewLogsService(logsRepository)
	logsHandler := controller.NewLogsHandler(logService)
	module := &Module{
		Svc: logService,
		Hdl: logsHandler,
	}
	return module
}

// wire.go:

var LogsProviders = wire.NewSet(controller.NewLogsHandler, service.NewLogsService, repo.NewLogsRepository, dao.NewLogsDao, wire.Bind(new(service.ILogsService), new(*service.LogService)), wire.Bind(new(repo.ILogsRepository), new(*repo.LogsRepository)), wire.Bind(new(dao.ILogsDao), new(*dao.LogsDao)))
