// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tags

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/tags/controller"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/tags/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/tags/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/tags/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitTagsModule() *Module {
	tagsDao := dao.NewTagsDao()
	tagsRepository := repo.NewTagRepository(tagsDao)
	tagService := service.NewTagService(tagsRepository)
	tagsHandler := controller.NewTagsHandler(tagService)
	module := &Module{
		Svc: tagService,
		Hdl: tagsHandler,
	}
	return module
}

// wire.go:

var TagsProviders = wire.NewSet(controller.NewTagsHandler, service.NewTagService, repo.NewTagRepository, dao.NewTagsDao, wire.Bind(new(service.ITagService), new(*service.TagService)), wire.Bind(new(repo.ITagsRepository), new(*repo.TagsRepository)), wire.Bind(new(dao.ITagsDao), new(*dao.TagsDao)))
