// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/users/controller"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/users/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/users/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/users/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUsersModule() *Module {
	userDao := dao.NewUserDao()
	userRepository := repo.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	userHandler := controller.NewUserHandler(userService)
	module := &Module{
		Svc: userService,
		Hdl: userHandler,
	}
	return module
}

// wire.go:

var UsersProviders = wire.NewSet(controller.NewUserHandler, service.NewUserService, repo.NewUserRepository, dao.NewUserDao, wire.Bind(new(service.IUserService), new(*service.UserService)), wire.Bind(new(repo.IUserRepository), new(*repo.UserRepository)), wire.Bind(new(dao.IUserDao), new(*dao.UserDao)))
