// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package posts

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/posts/controller"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/posts/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/posts/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/posts/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitPostModule(db *gorm.DB) *Module {
	postDao := dao.NewPostDao(db)
	postRepository := repo.NewPostRepository(postDao)
	postService := service.NewPostService(postRepository)
	postHandler := controller.NewPostHandler(postService)
	module := &Module{
		Svc: postService,
		Hdl: postHandler,
	}
	return module
}

// wire.go:

var PostProviders = wire.NewSet(controller.NewPostHandler, service.NewPostService, repo.NewPostRepository, dao.NewPostDao, wire.Bind(new(service.IPostService), new(*service.PostService)), wire.Bind(new(repo.IPostRepository), new(*repo.PostRepository)), wire.Bind(new(dao.IPostDao), new(*dao.PostDao)))
