// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post_category

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/post_category/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/post_category/repo/dao"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/post_category/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitPostCategoriesModule(db *gorm.DB) *Module {
	postCategoryDao := dao.NewPostCategoryDao(db)
	postCategoryRepository := repo.NewPostCategoryRepository(postCategoryDao)
	postCategoryService := service.NewPostCategoryService(postCategoryRepository)
	module := &Module{
		Svc: postCategoryService,
	}
	return module
}

// wire.go:

var PostCategoryProviders = wire.NewSet(service.NewPostCategoryService, repo.NewPostCategoryRepository, dao.NewPostCategoryDao, wire.Bind(new(service.IPostCategoryService), new(*service.PostCategoryService)), wire.Bind(new(repo.IPostCategoryRepository), new(*repo.PostCategoryRepository)), wire.Bind(new(dao.IPostCategoryDao), new(*dao.PostCategoryDao)))
