// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oss

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/oss/repo"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/oss/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitOssModule() *Module {
	ossRepository := repo.NewOssRepository()
	ossService := service.NewOssService(ossRepository)
	module := &Module{
		Svc: ossService,
	}
	return module
}

// wire.go:

var ossProviders = wire.NewSet(service.NewOssService, repo.NewOssRepository, wire.Bind(new(service.IOssService), new(*service.OssService)), wire.Bind(new(repo.IOssRepository), new(*repo.OssRepository)))
