// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package website

import (
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/stat"
	"github.com/dzsdbsdxq/dz-gin-blog/app/core/website/controller"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitWebModule(db *gorm.DB, statModule *stat.Module) *Module {
	iStatService := statModule.Svc
	webSiteHandler := controller.NewWebsiteHandler(iStatService)
	module := &Module{
		Hdl: webSiteHandler,
	}
	return module
}

// wire.go:

var WebProviders = wire.NewSet(controller.NewWebsiteHandler)
